### ISSUE TITLE
PHP fatal error when launch glpi sendMailLateReservations automatique schedule task

### ISSUE THREAD

**Issue by vlepetit** [salleman33/reservation#10]
Hi,

I am on GLPI 9.3.1 and reservation 2.1.0

When i want to launch glpi sendMailLateReservations automatique schedule task i had blanck screen on my web browser and this error log in /var/log/apache2/error.log 

PHP Fatal error:  Uncaught Error: Call to undefined method PluginReservationConfig::getConfigurationWeek() in /var/www/glpi/plugins/reservation/inc/task.class.php:144\nStack trace:\n#0 /var/www/glpi/plugins/reservation/inc/task.class.php(130): PluginReservationTask::sendMailLateReservations(Object(CronTask))\n#1 /var/www/glpi/inc/crontask.class.php(837): PluginReservationTask::cronSendMailLateReservations(Object(CronTask))\n#2 /var/www/glpi/front/crontask.form.php(49): CronTask::launch(-1, 1, 'sendMailLateRes...')\n#3 {main}\n  thrown in /var/www/glpi/plugins/reservation/inc/task.class.php on line 144, referer: https://support.univ-psl.fr/front/crontask.form.php?id=43

Could you help me to resolve this issue, please.

Regards,
vlepetit

**Comment by carlosribeiro** [comment]
I have the same problem

**Comment by MARIA-Romain** [comment]
I have the same problem

**Comment by salleman33** [comment]
Hi, 

you can delete this line (144 in file inc/task.class.php).

Regards

**Comment by vlepetit** [comment]
Hi,

when i comment line 144 in file inc/task.class.php : "$week = $config->getConfigurationWeek();"

I have another error in log : 
[Tue Jan 08 09:47:47.375375 2019] [:error] [pid 8152] [client 194.214.56.97:60259] PHP Fatal error:  Uncaught Error: Call to a member function getType() on array in /var/www/glpi/inc/notificationtarget.class.php:271\nStack trace:\n#0 /var/www/glpi/inc/notificationevent.class.php(114): NotificationTarget::getInstance(Array, 'plugin_reservat...', Array)\n#1 /var/www/glpi/plugins/reservation/inc/task.class.php(155): NotificationEvent::raiseEvent('plugin_reservat...', Array)\n#2 /var/www/glpi/plugins/reservation/inc/task.class.php(130): PluginReservationTask::sendMailLateReservations(Object(CronTask))\n#3 /var/www/glpi/inc/crontask.class.php(837): PluginReservationTask::cronSendMailLateReservations(Object(CronTask))\n#4 /var/www/glpi/front/crontask.form.php(49): CronTask::launch(-1, 1, 'sendMailLateRes...')\n#5 {main}\n  thrown in /var/www/glpi/inc/notificationtarget.class.php on line 271, referer: https://support.univ-psl.fr/front/crontask.form.php?id=43

Regards,
vlepetit

**Comment by dpareja2** [comment]
` PHP Fatal error:  Uncaught Error: Call to undefined method PluginReservationConfig::getConfigurationWeek() in /var/www/html/glpi/plugins/reservation/inc/task.class.php:144
Stack trace:
#0 /var/www/html/glpi/plugins/reservation/inc/task.class.php(130): PluginReservationTask::sendMailLateReservations(Object(CronTask))
#1 /var/www/html/glpi/inc/crontask.class.php(836): PluginReservationTask::cronSendMailLateReservations(Object(CronTask))
#2 /var/www/html/glpi/front/crontask.form.php(49): CronTask::launch(-1, 1, 'sendMailLateRes...')
#3 {main}
  thrown in /var/www/html/glpi/plugins/reservation/inc/task.class.php on line 144, referer: http://xxxxxxxx/front/crontask.form.php?id=42
`
This is after commenting that line 144
`
PHP Fatal error:  Uncaught Error: Call to a member function getType() on array in /var/www/html/glpi/inc/notificationtarget.class.php:271
Stack trace:
#0 /var/www/html/glpi/inc/notificationevent.class.php(114): NotificationTarget::getInstance(Array, 'plugin_reservat...', Array)
#1 /var/www/html/glpi/plugins/reservation/inc/task.class.php(155): NotificationEvent::raiseEvent('plugin_reservat...', Array)
#2 /var/www/html/glpi/plugins/reservation/inc/task.class.php(130): PluginReservationTask::sendMailLateReservations(Object(CronTask))
#3 /var/www/html/glpi/inc/crontask.class.php(836): PluginReservationTask::cronSendMailLateReservations(Object(CronTask))
#4 /var/www/html/glpi/front/crontask.form.php(49): CronTask::launch(-1, 1, 'sendMailLateRes...')
#5 {main}
  thrown in /var/www/html/glpi/inc/notificationtarget.class.php on line 271, referer: http://xxxxxxxxx/front/crontask.form.php?id=42
`

**Comment by flonou** [comment]
Hi,
Weekdays selection for e-mails was removed, @salleman33 do you plan on putting it back or removing it totally ?

**Comment by salleman33** [comment]
Hi, 
Could you change the line 154 : 
`if (NotificationEvent::raiseEvent('plugin_reservation_expiration', $reservation)) {`
as 
`if (NotificationEvent::raiseEvent('plugin_reservation_expiration', $res)) {`

**Comment by salleman33** [comment]
@flonou  :  I removed this functionality because it can be done with the config interface of automatic actions

**Comment by salleman33** [comment]
bug fixed on the v2.1.1
