### ISSUE TITLE
When a conflict in a reservation accours, notify both the previous and next reservation users

### ISSUE THREAD

**Issue by flonou** [salleman33/reservation#14]
For now, when a conflict occurs, only the user of the new reservation that is being delayed is notified
I would like to add a way to also notify the user of the conflicting previous reservations and allow the notification translation to handle the name of both users so that they know who is the other one

**Comment by salleman33** [comment]
conflict notifications use the GLPI core system with a reservation object. It's impossible to make what you want. But you can create an other notification event for previous owner and raise the event in the file task.class.php in the line 100, for exemple : 
`NotificationEvent::raiseEvent('plugin_reservation_conflict_previous_owner', $reservation);`

**Comment by salleman33** [comment]
feature add to 2.1.1

**Comment by salleman33** [comment]
I test this feature. The tag for "##reservation.otheruser##" doesn't work.
Do you test it ?

**Comment by flonou** [comment]
I did test it but not on the last version, I will look into it

**Comment by flonou** [comment]
Ok I got it, that's because glpi kind of has a bug with this kind of things.
The new commit should resolve it

**Comment by salleman33** [comment]
ok, thanks !
