### ISSUE TITLE
Notification for every event of Reservations, won't send email to requester

### ISSUE THREAD

**Issue by PowerShellPlace** [salleman33/reservation#20]
GLPI: 9.3.2
Plugin: 2.1.2

I have problem with notifiy requester by email from Reservation events.
For every possible event ex. Expired, Deleted, New etc.

I enabled in requester user profile "notifications for my changes" - nothing happened.
With new reservation I notify group, and that works fine. I see in queue that new reservation emails will be send to users from group, but not for requester.

I tryed almost everything, do you have any idea? 
Thanks for help

**Comment by salleman33** [comment]
Hi, 
You should better ask in the GLPI forum, your problem is not about the plugin Reservation.

Regards

**Comment by PowerShellPlace** [comment]
Hi,

Okay I will ask on GLPI forum, if I will get answer, will paste it here :)
