### ISSUE TITLE
Acquittement / checkout disappear ?

### ISSUE THREAD

**Issue by webafrancois** [salleman33/reservation#21]
Hello Sylvain,
We discover your plugin and want to use it in place of the reservation tool.
But we don't have found where the old reservations are stored. When we check the checkout, the reservation disappear and we don't find its anywhere.
Are they deleted ? Or can we see it in some options ?
We're thinking very useful to see who was the last people who take some material.
Thanks.

**Comment by salleman33** [comment]
Hi, 
You have to select the right range of dates.The begin date is the current time, if you checkout an item, it disappears because this action is past. Change the begin date in the form to display all reservation.

**Comment by webafrancois** [comment]
OK, thanks a lot for this tip !
