### ISSUE TITLE
Dosen't Install Plugins (Reservation)

### ISSUE THREAD

**Issue by lrodriguez31** [salleman33/reservation#23]
I need manual for install this plugins with send error when rename file in /var/www/html/glpi/plugins :

Bareword "reservation" not allowed while "strict subs" in use at (user-supplied code) line 3.

Who is the problem ?

**Comment by salleman33** [comment]
Hi, 
Does this error message occure after you type a command to rename file ? 
what command did you use ?

**Comment by lrodriguez31** [comment]
Yes

**Comment by lrodriguez31** [comment]
Change name with other command and Run,  Thank for Feedback....

**Comment by salleman33** [comment]
cool !
