### ISSUE TITLE
Tag not working in the notification

### ISSUE THREAD

**Issue by Lily971** [salleman33/reservation#24]
Hi !! 

My notification recaps who reserved what item so I've put the tag ##reservation.item## in my html code but it's not translated in the notification email. The other tags work just fine, it's the only one not working.

**Comment by salleman33** [comment]
HI, 
tags are not managed by the Reservation plugin. It's a GLPI core function. Neverless, I think you could use "##reservation.item.name##" instead of "##reservation.item##". I guess ##reservation.item## is a array to iterate over.
