### ISSUE TITLE
Error in the Check In/out

### ISSUE THREAD

**Issue by hmrito** [salleman33/reservation#25]
Hello, im having a trouble with the check in/out option, everytime i make a reservation the check in/out it came allready with the date, both of them..  (19-01-2038 à 03:14:07).

Could you help ?

**Comment by salleman33** [comment]
Hi, 
does the server have the right time?

**Comment by hmrito** [comment]
Hello
This last version solved my issue. I can now make the check in and the check out .

Thank you
