### ISSUE TITLE
Deleted object reserved create a bug

### ISSUE THREAD

**Issue by webafrancois** [salleman33/reservation#30]
We have made a reservation for an object. But we made a mistake for this object in a wrong category and have to delete it and create another in another category.
Actually our reservation show a reservation with the user account but any element in the user page.
In the reservation plugin, there is a problem because we don't see the others reservation. It seems like the empty element stop to list the others.

Some screenshots to show our problem.

![by-user](https://user-images.githubusercontent.com/19719849/72629273-479f2380-3950-11ea-8bd9-f5e7ab018ee0.png)

![no-element](https://user-images.githubusercontent.com/19719849/72629293-538ae580-3950-11ea-8a45-ac581a7809db.png)

**Comment by salleman33** [comment]
Hi, 
I note the bug and I try to check that ASAP...

**Comment by salleman33** [comment]
Hi, 
I cannot reproduce the bug. Could you describe how you do ? 
Which GLPI version are you using ?

**Comment by salleman33** [comment]
closed for inactivity
