### ISSUE TITLE
Impossible d'installer le plugin

### ISSUE THREAD

**Issue by Nemesisfr** [salleman33/reservation#32]
Bonjour, 
Je n'arrive pas a installer le plugins, j'ai la version 9.4.5 de glpi et j'ai essayé d'installer la version 2.2.0 et 2.0.0-rc2 dans mon dossier plugin mais ils ne sont toujours pas visible dans la liste des plugins à installer sur GLPI.

PS : j'ai essayé avec d'autre version mais cela ne fonctionne pas non plus

Pouvez vous m'aider svp
Merci beaucoup

**Comment by salleman33** [comment]
Bonjour, 
est-ce un probleme uniquement avec le plugin Reservation où cela concerne tous les plugins ?

**Comment by Nemesisfr** [comment]
Bonjour, 
Uniquement avec le plugin réservation, les autre s'installent correctement.

Merci en tout cas de votre retour rapide.

Cordialement.

**Comment by salleman33** [comment]
avez-vous verifier les droits sur le dossier ? que disent les logs ?

**Comment by Nemesisfr** [comment]
Oui j'ai les droits sur le doosier, pour preuve les autres plugins fonctionnent.

Les logs se trouvent ils bien dans files/logs ? J'ai divers logs sur la migration, cron event mais rien sur le plugins

**Comment by salleman33** [comment]
Il faut que le serveur web ait les droits de lecture sur le dossier (apache, nginx, etc.)
les logs devraient etre dans php-errors.log
est-ce que l'arboscence du dossier plugins est correct ? il doit y avoir par exemple le chemin "glpi/plugins/reservation/setup.php"

**Comment by Nemesisfr** [comment]
Je viens de trouver le fichier : 
Voici les logs

plugin_version_reservation-2.0.1 method must be defined!  {"user":"7@Samadata2"} 
[2020-03-04 12:19:54] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1238
plugin_version_reservation-2.0.1 method must be defined!  {"user":"7@Samadata2"} 
[2020-03-04 12:19:58] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1238
plugin_version_reservation-2.0.1 method must be defined!  {"user":"7@Samadata2"} 
[2020-03-04 12:20:00] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1238
plugin_version_reservation-2.0.1 method must be defined!  {"user":"7@Samadata2"}

**Comment by salleman33** [comment]
modifiez le nom du dossier reservation-2.2.0 en reservation tout simplement

**Comment by Nemesisfr** [comment]
Super cela fonctionne.
Merci beaucoup.
