### ISSUE TITLE
[Question] Acquitement après fin de réservation

### ISSUE THREAD

**Issue by Nemesisfr** [salleman33/reservation#33]
Bonjour,

Je viens de m'apercevoir qu'il est possible d'acquiter le matériel lorsque celui ci n'est pas encore arrivé à la fin de la réservation mais lorsque celui ci est est dépassé le matériel disparait de la liste. Comment puis-je voir toutes les réservations dont le matériel n'est pas rendu svp.

Merci

**Comment by salleman33** [comment]
il disparait si la tache automatique de prolongation ne s'est pas declanchée.  Je vous conseille de lire le README pour comprendre le fonctionnement.
