### ISSUE TITLE
Reservations for GLPI 9.5

### ISSUE THREAD

**Issue by orgdv** [salleman33/reservation#35]
we use the Reseration plugin in GLPI version 9.4. is the plugin also compatible with version 9.5 or is there a timetable for adaptation to version 9.5? Thanks a lot.

**Comment by salleman33** [comment]
Hi, 
do you try to use it with GLPI 9.5 ?

**Comment by HynekPetrak** [comment]
Hello,
I tested with version 9.5 and it does not load. Is there a log file to look into?

**Comment by salleman33** [comment]
Yes, you can watch in glpi location, folder files/_log

**Comment by salleman33** [comment]
Hi, I just tried installing the plugin on GLPI 9.5 and it works. Do you still have your problem?

**Comment by salleman33** [comment]
closed for inactivity
