### ISSUE TITLE
error after upgrade to glpi 9.5.2

### ISSUE THREAD

**Issue by carlosribeiro** [salleman33/reservation#37]
after upgrade to glpi 9.5.2 and upgrade plugin reservation occurred error on open plugin.
this error: 

Deprecated: Use DBmysql::fetchAssoc() in C:\xampp\htdocs\glpi\inc\toolbox.class.php on line 632

**Comment by salleman33** [comment]
Hi, 
It seems that it is an error with GLPI Core and the toolbox class.

**Comment by carlosribeiro** [comment]
PHP Log:
 Backtrace :
  inc\toolbox.class.php:632                          trigger_error()
  inc\dbmysql.class.php:484                          Toolbox::deprecated()
  plugins\reservation\inc\reservation.class.php:131  DBmysql->fetch_assoc()
  plugins\reservation\inc\menu.class.php:389         PluginReservationReservation::getAvailablesItems()
  plugins\reservation\inc\menu.class.php:228         PluginReservationMenu::displayTabReservations()
  plugins\reservation\inc\menu.class.php:170         PluginReservationMenu::displayTabContentForCurrentReservations()
  inc\commonglpi.class.php:637                       PluginReservationMenu::displayTabContentForItem()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()

**Comment by carlosribeiro** [comment]
solution?

**Comment by salleman33** [comment]
Hi, 
could you try this : https://github.com/salleman33/reservation/issues/40#issuecomment-742399050

**Comment by salleman33** [comment]
resolved with https://github.com/salleman33/reservation/commit/15baf63127e98131db73d51e1609011a0396e48e
