### ISSUE TITLE
L'extension automatique des items non retournés ne fonctionne pas

### ISSUE THREAD

**Issue by eccal** [salleman33/reservation#38]
Cette fonctionnalité fonctionnais bien en version 1.4.3.
Mais depuis que je suis passé à la version du plugin 2.3.3, les ordinateurs qui passent en expiré, au lieu de passer en rouge et d'être prolongé par exemple à chaque pas de 5 minutes, la réservation est automatiquement considéré comme rendu.

Comment remédier à cela ?

Merci

**Comment by salleman33** [comment]
Bonjour, 

avez-vous essayer de désinstaller puis réinstaller le plugin ?

**Comment by eccal** [comment]
Bonjour,
Oui j'ai déjà essayé cela.

Je viens de tester à l'instant sur un serveur de test (glpi 9.4.6) avec le plugin en version 2.2.0. Puis j'ai testé au cas où deux autres version du plugin (2.1.2 et 2.3.3) pour vérifier si cela ne venait pas de cela, et le constat est le même.

Il y a peut être une option pour activer cette fonctionnalité que j'aurais manqué ?

**Comment by salleman33** [comment]
est-ce que la tache automatique de lance correctement ?

**Comment by eccal** [comment]
Effectivement le problème venait bien de là.
Bizarrement la tâche automatique du plugin était resté "coincé" sur "en cours d'exécution" indéfiniment.
Le seul moyen de la faire repartir à été de passé  temporairement en mode d'exécution "glpi" avant de repartir sur le mode "cli".

En tout cas merci, j'avais pas fait assez attention à ce point là.
