### ISSUE TITLE
Reservation installation sur GLPI 9.5.1

### ISSUE THREAD

**Issue by Nicolas-ld** [salleman33/reservation#39]
Bonjour,

L'installation du plugin ne fonctionne pas sur la version 9.5.1 de GLPI.
Le fichier php-errors.log marque
 glpiphplog.ERROR: Plugin::getInfo() in /var/www/glpi9.5.1/inc/plugin.class.php line 1394
plugin_version_reservation-2.3.3 method must be defined!  {"user":"260@srvglpi"}

Merci de votre aide.

**Comment by Nicolas-ld** [comment]
Passage en version 9.5.2 de GLPI : Problème identique

**Comment by salleman33** [comment]
bonjour, 
j'ai retiré la compatibilité pour la version 9.5 en attendant de voir d'où vient le problème
il faut que je trouve du temps pour ça...

**Comment by salleman33** [comment]
ok, je viens de voir quel est le problème. Il faut renommer votre répertoire glpi/plugins/reservation-2.3.3 en glpi/plugins/reservation
