### ISSUE TITLE
erreur toolbax.class.php ligne 632

### ISSUE THREAD

**Issue by jcovillers78114** [salleman33/reservation#40]
Deprecated: Use DBmysql::fetchAssoc() in C:\xampp\htdocs\glpi\inc\toolbox.class.php on line 632

Voici le message d'erreur affiché sur toute la page...

Glpi 9.5.2

![image](https://user-images.githubusercontent.com/57490677/98246118-23114800-1f72-11eb-98df-8ad9116609ca.png)

**Comment by chichtacos** [comment]
Hi, 

I had the same issue.
I "solved" it by replacing fetch_assoc (which is deprecated now)  with fetchAssoc in the following files : 

In reservation/inc/ :

category.class.php
category.item.class.php
config.class.php
menu.class.php
reservation.class.php

Exemple in category.class.php
 46 - //while ($row = $DB->fetch_assoc($result)) {
46 +			while ($row = $DB->fetchAssoc($result)) {

**Comment by salleman33** [comment]
Thanks !
I am going to add that and make a new release.
