### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by magheinz** [salleman33/reservation#41]
API-Calls not working:
 PHP Fatal error:  Uncaught Error: Class 'API' not found in /var/www/glpi-9.5.2/plugins/reservation/inc/api.php:9

**Comment by magheinz** [comment]
Added use Glpi\Api\API; to inc/api.php and it seams to work.
I have now a porblem with PUT and the data-field...

**Comment by salleman33** [comment]
Hi, 
Could you detail your problem with PUT requests ? What is your code, your request ?

**Comment by magheinz** [comment]
Now, also PUT works.
Problem was something with the Data-Array.

Great work, this plugin.

So, only "use GLPI\Api\API;" in in/api.php is necessary for GLPI 9.5.2.
