### ISSUE TITLE
Problem reservation 2.3.3 on GLPI 9.4.5

### ISSUE THREAD

**Issue by willianfrs** [salleman33/reservation#42]
I'm having problems with the reservation plugin version 2.3.3. It stopped working, on the plugins administration screen, this one has an error / clear status. I try to click the button to do the cleaning, the screen keeps loading and error 504 Gateway Time-Out returns.

How can I resolve this case? Thank you very much. 

![image](https://user-images.githubusercontent.com/47404981/114213900-02428980-993a-11eb-96c7-998274cbed37.png)

**Comment by salleman33** [comment]
Hi, 
Could you check the log in glpi/files/_log/php-errors.log ?

**Comment by willianfrs** [comment]
Thanks a lot for the help. I was able to solve it, I ended up removing the plugin folder and downloading it again. It's working.
Thank you again.
