### ISSUE TITLE
suggestion notification

### ISSUE THREAD

**Issue by El-Salmon60** [salleman33/reservation#43]
Bonjour, serait il possible de créer une notification spécialement pour la fonction checkin car actuellement elle fait parti de la notification de modification de la réservation et cela serait plus pratique de les séparer.

Merci.

**Comment by salleman33** [comment]
Bonjour, 
Pour ne rien vous cacher, je n'ai plus le temps de développer de nouvelles fonctionnalités. J'ai juste le temps de le maintenir pour suivre les mises à jours de GLPI.

**Comment by salleman33** [comment]
Bonjour, 
j'ai ajouté une notification pour l'action checkin. Mais il y aura toujours la notification de mise à jour de la réservation, ici je ne pourrais pas faire grand chose car je m'appuie sur les fonctions du coeur de glpi pour mettre à jour la réservation.
