### ISSUE TITLE
Utilisation API

### ISSUE THREAD

**Issue by psableyrolles** [salleman33/reservation#44]
Bonjour,

   Je souhaiterais utiliser votre plugin pour créer une gestion des disponibilité des postes de travail dans l'entreprise dans laquelle je travaille. Pour faciliter la visibilité je souhaiterais extraire les informations relatives aux réservations en utilisant l'API que vous avez développé pour afficher les afficher sous forme de plan avec les tables et noms des employées. 

   Néanmoins j'ai quelques problèmes dans l'utilisation de l'API :
   - j'arrive à sortir l'ensemble des réservations (GET ...apirest.php/reservation) mais je n'arrive pas à utiliser les fonctions présentent dans le fichier api.php (currentReservation, nextReservation ... ),  ces fonctions pourraient répondre à un besoin de mon entreprise
   - en modifiant un peu le fichier api.php je me suis rendu compte que mes modifications ne changeaient pas le comportement de l'api (le fichier api.php est-il utilisé par l'api ou est-ce un autre ?)
   - en essayant de comprendre le fichier api.php je n'ai pas réussi à trouver la référence de la bibliothèque utilisé Glpi\Api\API utilisé pour la classe PluginReservationApi

**Comment by salleman33** [comment]
Bonjour, 
voici un exemple de code que j'utilise sur une application python, peut-être que ça pourra vous aider, notamment au niveau de l'URL à utiliser pour interroger l'API

```python
GLPI_API = 'https://monserveur/glpi/apirest.php/'
PLUGIN_API = GLPI_API + '../plugins/reservation/apirest.php/'

class RestClient(object):
    headers = {}

    # demarre la session
    def __init__(self):
        self.headers = {
            'App-Token': 'xxxxx',
            'Authorization':'user_token xxxxx',
            'Content-Type': 'application/json'
        }
        resp = requests.get(GLPI_API + 'initSession', headers=self.headers)
        resp.raise_for_status() # exception si code != 200
        del self.headers['Authorization']
        self.headers.update({"Session-Token": resp.json()['session_token']})

   def getCurrentReservationForReservationItem(self, id):
        resp = requests.get(PLUGIN_API + 'reservationItem/currentReservation/' + str(id), headers=self.headers)
        if(resp.ok):
            return resp.json()
        elif (resp.status_code == 404):
            return None
        else:
            resp.raise_for_status()

```

**Comment by psableyrolles** [comment]
Merci pour votre réponse,
j'avais en effet un soucis au niveau de mon URL.
