### ISSUE TITLE
Glpi Version 9.4.5 and Reservation 2.3.5 not opening

### ISSUE THREAD

**Issue by chammachamma** [salleman33/reservation#45]
Hi! 

Could you please help me? As soon as I click on Plugins-Reservation it shows:

There was a problem loading 
Please check GLPI´s Logs or contatct admin.

Any ideas please?

Best Regards

**Comment by salleman33** [comment]
Hi, 
Could you check the logs in glpi/files/_log/ ?

**Comment by chammachamma** [comment]
Hi!

Thanks for your help.

Yes, I have already checked them, no clue..

Any Other idea please?

Att,



De: Allemand ***@***.***>
Enviada em: quarta-feira, 5 de maio de 2021 07:41
Para: salleman33/reservation ***@***.***>
Cc: Marcos Chamma ***@***.***>; Author ***@***.***>
Assunto: Re: [salleman33/reservation] Glpi Version 9.4.5 and Reservation 2.3.5 not opening (#45)


Hi,
Could you check the logs in glpi/files/_log/ ?

**Comment by salleman33** [comment]
Could you paste the content of  php-erros.log file after trying to click on plugins > reservations

**Comment by salleman33** [comment]
you can try to uninstall and install again and check log files

**Comment by chammachamma** [comment]
Hi!


***@***.*** _log]# tail -f php-errors.log
  *** PHP Notice(8): Undefined index: telegram_username
  Backtrace :
  plugins/telegrambot/inc/user.class.php:52
  plugins/telegrambot/inc/user.class.php:65          PluginTelegrambotUser::item_add_user()
  :                                                  PluginTelegrambotUser::item_update_user()
  inc/plugin.class.php:1112                          call_user_func()
  inc/commondbtm.class.php:1355                      Plugin::doHook()
  inc/auth.class.php:819                             CommonDBTM->update()
  front/login.php:84                                 Auth->login()
  ***@***.***"}
[2021-05-05 08:43:59] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: telegram_username
  Backtrace :
  plugins/telegrambot/inc/user.class.php:52
  plugins/telegrambot/inc/user.class.php:65          PluginTelegrambotUser::item_add_user()
  :                                                  PluginTelegrambotUser::item_update_user()
  inc/plugin.class.php:1112                          call_user_func()
  inc/commondbtm.class.php:1355                      Plugin::doHook()
  inc/savedsearch.class.php:781                      CommonDBTM->update()
  ajax/savedsearch.php:108                           SavedSearch->displayMine()
  ***@***.***"}
^C
***@***.*** _log]# ls
php-errors.log
***@***.*** _log]# ls
php-errors.log
***@***.*** _log]# ls
php-errors.log
***@***.*** _log]# ls
php-errors.log
***@***.*** _log]# ls
php-errors.log
***@***.*** _log]# ls
php-errors.log
***@***.*** _log]# lsls
bash: lsls: command not found
***@***.*** _log]# ls
php-errors.log
***@***.*** _log]# ls
php-errors.log  sql-errors.log
***@***.*** _log]# vi sql-errors.log
***@***.*** _log]# tail -f sql-errors.log
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.658\", 12.10Mio)"}
[2021-05-05 08:50:01] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: TRUNCATE `glpi_notimportedemails`
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/notimportedemail.class.php:214
  inc/mailcollector.class.php:1779                   NotImportedEmail::deleteLog()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***"}
[2021-05-05 08:50:02] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '1'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.211\", 12.10Mio)"}
[2021-05-05 08:50:05] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '2'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"2.443\", 12.10Mio)"}
[2021-05-05 08:50:06] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '3'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.552\", 12.10Mio)"}
[2021-05-05 08:50:08] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '4'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.636\", 12.10Mio)"}
[2021-05-05 08:50:10] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '5'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.675\", 12.10Mio)"}
[2021-05-05 08:50:11] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '6'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.507\", 12.10Mio)"}
[2021-05-05 08:50:13] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '7'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.595\", 12.10Mio)"}
[2021-05-05 08:50:14] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '8'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.497\", 12.10Mio)"}
[2021-05-05 08:50:16] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '9'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.663\", 12.10Mio)"}
[2021-05-05 08:50:17] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '12'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.561\", 12.10Mio)"}
[2021-05-05 08:50:19] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '13'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.592\", 12.11Mio)"}
[2021-05-05 08:50:21] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_notimportedemails`.`id` FROM `glpi_notimportedemails` WHERE `mailcollectors_id` = '14'
  Error: Table 'glpi.glpi_notimportedemails' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:4301                      DBmysql->request()
  inc/mailcollector.class.php:663                    CommonDBTM->deleteByCriteria()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:77                                  CronTask::launch()
  ***@***.***","mem_usage":"1.589\", 12.11Mio)"}
^C
***@***.*** _log]# tail -f php-errors.log
  plugins/telegrambot/inc/user.class.php:52
  plugins/telegrambot/inc/user.class.php:65          PluginTelegrambotUser::item_add_user()
  :                                                  PluginTelegrambotUser::item_update_user()
  inc/plugin.class.php:1112                          call_user_func()
  inc/commondbtm.class.php:1355                      Plugin::doHook()
  inc/auth.class.php:819                             CommonDBTM->update()
  inc/api.class.php:239                              Auth->login()
  inc/apirest.class.php:135                          API->initSession()
  apirest.php:48                                     APIRest->call()
  ***@***.***"}
[2021-05-05 08:56:01] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: telegram_username
  Backtrace :
  plugins/telegrambot/inc/user.class.php:52
  plugins/telegrambot/inc/user.class.php:65          PluginTelegrambotUser::item_add_user()
  :                                                  PluginTelegrambotUser::item_update_user()
  inc/plugin.class.php:1112                          call_user_func()
  inc/commondbtm.class.php:1355                      Plugin::doHook()
  inc/auth.class.php:819                             CommonDBTM->update()
  inc/api.class.php:239                              Auth->login()
  inc/apirest.class.php:135                          API->initSession()
  apirest.php:48                                     APIRest->call()
  ***@***.***"}
[2021-05-05 08:56:01] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: telegram_username
  Backtrace :
  plugins/telegrambot/inc/user.class.php:52
  plugins/telegrambot/inc/user.class.php:65          PluginTelegrambotUser::item_add_user()
  :                                                  PluginTelegrambotUser::item_update_user()
  inc/plugin.class.php:1112                          call_user_func()
  inc/commondbtm.class.php:1355                      Plugin::doHook()
  inc/auth.class.php:819                             CommonDBTM->update()
  inc/api.class.php:239                              Auth->login()
  inc/apirest.class.php:135                          API->initSession()
  apirest.php:48                                     APIRest->call()
  ***@***.***"}
[2021-05-05 08:56:17] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined variable: ticket
  Backtrace :
  ...tificationtargetcommonitilobject.class.php:1411
  inc/notificationtargetticket.class.php:571         NotificationTargetCommonITILObject->getTags()
  ...otificationtargetcommonitilobject.class.php:923 NotificationTargetTicket->getTags()
  inc/notificationtarget.class.php:1236              NotificationTargetCommonITILObject->addDataForTemplate()
  inc/notificationtemplate.class.php:254             NotificationTarget->getForTemplate()
  inc/notificationeventabstract.class.php:108        NotificationTemplate->getTemplateByLanguage()
  inc/notificationevent.class.php:164                NotificationEventAbstract::raise()
  inc/itilfollowup.class.php:275                     NotificationEvent::raiseEvent()
  inc/commondbtm.class.php:1136                      ITILFollowup->post_addItem()
  front/itilfollowup.form.php:49                     CommonDBTM->add()
  ***@***.***"}
[2021-05-05 08:56:17] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined variable: ticket
  Backtrace :
  ...tificationtargetcommonitilobject.class.php:1412
  inc/notificationtargetticket.class.php:571         NotificationTargetCommonITILObject->getTags()
  ...otificationtargetcommonitilobject.class.php:923 NotificationTargetTicket->getTags()
  inc/notificationtarget.class.php:1236              NotificationTargetCommonITILObject->addDataForTemplate()
  inc/notificationtemplate.class.php:254             NotificationTarget->getForTemplate()
  inc/notificationeventabstract.class.php:108        NotificationTemplate->getTemplateByLanguage()
  inc/notificationevent.class.php:164                NotificationEventAbstract::raise()
  inc/itilfollowup.class.php:275                     NotificationEvent::raiseEvent()
  inc/commondbtm.class.php:1136                      ITILFollowup->post_addItem()
  front/itilfollowup.form.php:49                     CommonDBTM->add()
  ***@***.***","mem_usage":"0.000\", 8.40Mio)"}
[2021-05-05 08:56:18] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined variable: ticket
  Backtrace :
  ...tificationtargetcommonitilobject.class.php:1411
  inc/notificationtargetticket.class.php:571         NotificationTargetCommonITILObject->getTags()
  ...otificationtargetcommonitilobject.class.php:923 NotificationTargetTicket->getTags()
  inc/notificationtarget.class.php:1236              NotificationTargetCommonITILObject->addDataForTemplate()
  inc/notificationtemplate.class.php:254             NotificationTarget->getForTemplate()
  inc/notificationeventabstract.class.php:108        NotificationTemplate->getTemplateByLanguage()
  inc/notificationevent.class.php:164                NotificationEventAbstract::raise()
  inc/itilfollowup.class.php:275                     NotificationEvent::raiseEvent()
  inc/commondbtm.class.php:1136                      ITILFollowup->post_addItem()
  front/itilfollowup.form.php:49                     CommonDBTM->add()
  ***@***.***","mem_usage":"0.056\", 9.09Mio)"}
[2021-05-05 08:56:18] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined variable: ticket
  Backtrace :
  ...tificationtargetcommonitilobject.class.php:1412
  inc/notificationtargetticket.class.php:571         NotificationTargetCommonITILObject->getTags()
  ...otificationtargetcommonitilobject.class.php:923 NotificationTargetTicket->getTags()
  inc/notificationtarget.class.php:1236              NotificationTargetCommonITILObject->addDataForTemplate()
  inc/notificationtemplate.class.php:254             NotificationTarget->getForTemplate()
  inc/notificationeventabstract.class.php:108        NotificationTemplate->getTemplateByLanguage()
  inc/notificationevent.class.php:164                NotificationEventAbstract::raise()
  inc/itilfollowup.class.php:275                     NotificationEvent::raiseEvent()
  inc/commondbtm.class.php:1136                      ITILFollowup->post_addItem()
  front/itilfollowup.form.php:49                     CommonDBTM->add()
  ***@***.***","mem_usage":"0.000\", 9.09Mio)"}
[2021-05-05 08:57:02] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: telegram_username
  Backtrace :
  plugins/telegrambot/inc/user.class.php:52
  plugins/telegrambot/inc/user.class.php:65          PluginTelegrambotUser::item_add_user()
  :                                                  PluginTelegrambotUser::item_update_user()
  inc/plugin.class.php:1112                          call_user_func()
  inc/commondbtm.class.php:1355                      Plugin::doHook()
  inc/auth.class.php:819                             CommonDBTM->update()
  inc/api.class.php:239                              Auth->login()
  inc/apirest.class.php:135                          API->initSession()
  apirest.php:48                                     APIRest->call()
  ***@***.***"}


Thanks!!

De: Allemand ***@***.***>
Enviada em: quarta-feira, 5 de maio de 2021 08:53
Para: salleman33/reservation ***@***.***>
Cc: Marcos Chamma ***@***.***>; Author ***@***.***>
Assunto: Re: [salleman33/reservation] Glpi Version 9.4.5 and Reservation 2.3.5 not opening (#45)


Could you paste the content of php-erros.log file after trying to click on plugins > reservations

**Comment by salleman33** [comment]
ok... 
I cannot help you without more informations. Check apache/nginx logs files, enable debug mode on glpi.

**Comment by chammachamma** [comment]
Hi!

Does this help?

[Wed May 05 09:31:35.258485 2021] [:error] [pid 31458] [client 138.219.197.65:53934] PHP Fatal error:  Call to undefined method DB::fetchAssoc() in /var/www/html/glpi/plugins/reservation/inc/config.class.php on line 19, referer: https://chamati.net.br/front/plugin.php
[Wed May 05 09:31:51.637743 2021] [:error] [pid 31438] [client 138.219.197.65:53948] PHP Fatal error:  Call to undefined method DB::fetchAssoc() in /var/www/html/glpi/plugins/reservation/inc/reservation.class.php on line 76, referer: https://chamati.net.br/plugins/reservation/front/menu.php
~

Regards


De: Allemand ***@***.***>
Enviada em: quarta-feira, 5 de maio de 2021 09:13
Para: salleman33/reservation ***@***.***>
Cc: Marcos Chamma ***@***.***>; Author ***@***.***>
Assunto: Re: [salleman33/reservation] Glpi Version 9.4.5 and Reservation 2.3.5 not opening (#45)


ok...
I cannot help you without more informations. Check apache/nginx logs files, enable debug mode on glpi.

**Comment by salleman33** [comment]
yes : 
reservation v2.3.5  is compatible with GLPI 9.5. 
For GLPI 9.4, you can use reservation v2.3.3

I'm going to update the compatibility checks to avoid this problem

**Comment by chammachamma** [comment]
Thank you very Much for your prompt return.

Now it is working!



De: Allemand ***@***.***>
Enviada em: quarta-feira, 5 de maio de 2021 09:49
Para: salleman33/reservation ***@***.***>
Cc: Marcos Chamma ***@***.***>; Author ***@***.***>
Assunto: Re: [salleman33/reservation] Glpi Version 9.4.5 and Reservation 2.3.5 not opening (#45)


yes :
reservation v2.3.5 is compatible with GLPI 9.5.
For GLPI 9.4, you can use reservation v2.3.3

I'm going to update the compatibility checks to avoid this problem
