### ISSUE TITLE
Custom Categories 

### ISSUE THREAD

**Issue by Binder-F** [salleman33/reservation#47]
Hello

I would like create Custom Categories but the devices are invisable. I can't see any devices on the Configure Site.

**Comment by salleman33** [comment]
Hi,
which version of GLPI and reservation plugin are you using ?

**Comment by Binder-F** [comment]
Hi,

GLPI = 9.5.6 and Reservation = 2.3.5

**Comment by Binder-F** [comment]
In the php log is no error but in the sql-error.log

MySQL Error 
...
Error: Incorrect DATETIME value

**Comment by salleman33** [comment]
Just in case, do you have at least one reservation item ?
