### ISSUE TITLE
[9.5.5]Conflicting schedules set to delay but is deleting instead

### ISSUE THREAD

**Issue by felipebart10** [salleman33/reservation#49]
I've set the configuration to delay next reservation when the current reservation delays on its checkout, but the plug-in keeps deleting the next reservation. I'm currently using the latest plug-in version. Is there a fix? We're currently seeing the possibility to implement this plug-in in our IT sector but this inconsistency is critical. Thanks in advance!

**Comment by salleman33** [comment]
Hi, 
Could you paste the last content of the log file. You can find it in glpi/files/_log/reservations_plugin.log

**Comment by salleman33** [comment]
I just release the version 2.3.6 with some bug fixes. Could you try with it please ?

**Comment by felipebart10** [comment]
Hi!!
I will run a test with the updated version and if the error persists I will put the log here. Thanks!

**Comment by felipebart10** [comment]
@salleman33, I've updated but the issue keeps happening. I've created two reservations for the same device, with one from **08:19-08:21, id 1880** and another from **08:21-08:23, id 1878** (please ignore id 1858, it's another device, it was just postponed within this cron task). As we can see, reservation **1878 couldn't be updated and was terminally excluded**. One thing I noticed is that the action is updating to a weird end-time (13:21), so a two minute reservation is turning into a five hours one. Could this be related to some timezones conflict? This happened with the remaining reservations 1880 and 1858. If you want another info, let me know. Thanks :)

![1](https://user-images.githubusercontent.com/64552706/139665062-1c16d62f-9859-42cf-92de-5e76fd71fcb7.PNG)

**Comment by felipebart10** [comment]
Created another test reservations and printed before and after the postpone: 
![3](https://user-images.githubusercontent.com/64552706/139667817-7d641157-975c-4dd2-b7b0-d3b00530c5d8.PNG)

![5](https://user-images.githubusercontent.com/64552706/139667794-a58bc358-0013-4932-8a35-881f984535a1.PNG)

![4](https://user-images.githubusercontent.com/64552706/139667827-e1b9559e-da8d-43a0-b339-d0e2c9371a30.PNG)

**Comment by felipebart10** [comment]
I do not know much about PHP and the GLPI plugins architeture, but I think this is happening because a time manipulation issue. This test `if ($conflict_reservation->fields["end"] <= $end_plus_epsilon) {` is returning true for every reservation to delay and is ultimately deleting it
                  

>            switch ($conflict_action) {
>               case "delete":
>                  $task->log("Deleting reservation " . $conflict_reservation->fields['id'] . " on item ". $item->fields['name']);
>                  $conflict_reservation->delete(['id' => $conflict_reservation->fields['id']]);
>                  break;
>               case "delay":
>		  $end_plus_epsilon = date("Y-m-d H:i:s", $time + $delay + ($delay / 2));
>                  if ($conflict_reservation->fields["end"] <= $end_plus_epsilon) {
>                     $task->log("Could not delay reservation " . $conflict_reservation->fields['id'] . " on item ". $item->fields['name']);
>                     $conflict_reservation->delete(['id' => $conflict_reservation->fields['id']]);
>                     break;
>                  }
>                  $query = "UPDATE `glpi_reservations`
>                        SET `begin` = '".$end."'
>                        WHERE `id`='" . $conflict_reservation->fields["id"] . "'";
>                  $DB->query($query) or die("error on 'update' into checkReservations conflict to delay start of a reservation : " . >$DB->error());
>                  $task->log("Delaying reservation " . $conflict_reservation->fields['id'] . " on item ". $item->fields['name']);
>                  break;
>            }

**Comment by salleman33** [comment]
Hi,
I think the end date of your tests reservations is wrong: when the plugin is set to delay conflicted reservations, if the end date is earlier than the next scheduled task, it removes the booking conflict instead of delay it.
I made this choice because delay the beginning date is easy. Delay the end date is more complicated, it could be an other conflict with some reservations, etc. 

could you check frequency of the schedule task "checkReservations" ?

**Comment by felipebart10** [comment]
Thanks for reply, @salleman33 

checkReservations is being executed every minute. 

I do not understand why my end dates are wrong. Let's say I have two revervations: one from 09-10am and another from 10-11am (they are similar from the screened example I've posted above). Both seems ok, but what will happen is that the first one will be stretched (this part is the expected behaviour) and the later one will be excluded (it should've been delayed). Will keep looking the cause of it.

**Comment by salleman33** [comment]
Could you give me the value of your "Step for the hours (minutes)" in Setup > general > assistance ?

**Comment by felipebart10** [comment]
Yes!
Step for the hours (minutes): 1 minute
(plugin) Duration add (in hour) to reservations expiring and not checkout: "default"

**Comment by salleman33** [comment]
You are right, it seems you use the UTC timezone. You can change it in your php.ini file, set the value for "date.timezone" (http://php.net/date.timezone)

**Comment by felipebart10** [comment]
Nice! I've changed the config and now the endtime timestamp is updating to the correct time.

But I'm doing some tests and noticed that the automatic action to postpone the reservations is not working properly in some cases. I will list two examples below.

Let's say we have these types of schedule to a generic equipment:

> `Reservation 1: 09:00 to 09:05`
> `Reservation 2: 09:05 to 09:10`
> _In this case, When Reservation 1 extends after 09:05, Reservation 2 will be postponed as intended :-)_


> `Reservation 1: 09:00 to 09:05`
> `Reservation 2: 09:05 to 09:10`
> `Reservation 3: 09:10 to 09:15`
> _Now in this case, what is happening is that Reservation 1 will be extended, but Reservation 2 will be deleted and Reservation 3 will keep its schedule the same. If we keep Reservation 1 opened until it reaches Reservation 3, then Reservation 3 will be postponed as intended._ 

**By analysing the log, I think the routine is doing something incorrect in the bolded task listed below:**

> Step 1: Check if Reservation 1 is overdued
> Step 2: Check if it will get in conflict with a subsequent reservation
> **Step 3: Detect Reservaiton 2 and try to postpone it** (here Reservation 2 will be deleted, which is incorrect) 
  

So when we have two subsequent reservations, routine works like a charm, but when we have 3 or more, the routines isn't doing this verification. What is happening according logs is when the routine tries to postpone Reservation 2, it is getting in conflict with Reservation 3. Maybe a solution could be starting to execute the routine from the last subsequent reservation to the first (in this case, postpone Reservation 3 first and then postpone Reservation 2) but this is just a guess. Will try myself to find something in the code too. Thanks in advance!

**Comment by mahanovi** [comment]
Hi,

it seems that I have a similar problem.

Whenever the task "checkReservations" runs, it extends the current reservation by hours and deletes the following reservation.

My timezone is Europe/Berlin.

What do I have to change in my settings to get this running?

Thank in advance!

**Comment by salleman33** [comment]
Hi, 
Could you give me the value of your "Step for the hours (minutes)" in Setup > general > assistance, 
and the value in plugin setup for "Duration added (in hour) to reservations expiring and not checkout".
Could you paste the log of the task which extends the reservation and deletes the following reservation.

**Comment by mahanovi** [comment]
Sure!
Step for the hours (minutes) is 5,
Duration added (in hour) to reservations expiring and not checkout is 1
![image](https://user-images.githubusercontent.com/95433276/144572388-9fa6265d-baba-4254-a116-46cb53013024.png)

**Comment by salleman33** [comment]
@felipebart10 
Here is the code who deletes the reservation instead of delays it : 
```
if ($conflict_reservation->fields["end"] <= $end_plus_epsilon) {
                     $task->log("Could not delay reservation " . $conflict_reservation->fields['id'] . " on item ". $item->fields['name']);
                     $conflict_reservation->delete(['id' => $conflict_reservation->fields['id']]);
                     break;
                  }
```
It deletes it only if the end of conflicted reservation is earlier than end of "time between 2 schedule tasks".
Is this your case?

**Comment by salleman33** [comment]
@mahanovi 
Ok, it's normal : the task is running at 9:41 and check the range time until 10:41, and try to extends reservations after 10:41. But your reservation 23 is ending at 10:21 !
