### ISSUE TITLE
(German?) Translation

### ISSUE THREAD

**Issue by mahanovi** [salleman33/reservation#54]
We have noticed that the plugin has not yet been properly translated into German.

Maybe we can help here.

Is there any way that we can work on a translation ourselves? How is thisimplemented into the plugin?

Sorry for the beginner's question, but we are still making our first experiences in GLPI ourselves.

**Comment by salleman33** [comment]
Yes, you can copy the file locales/glpi.pot and create the file 'de_DE.po'
After, you have to complete each "msgstr' with the german translations. 
To compile locales, you can use the script in tools/update_mo.pl

You can make a pull-request in github with your new translation file. 
Thanks !

**Comment by mahanovi** [comment]
Hi,

I completed a first draft of the translation.

But now I don't know how to properly use the update_mo.pl script.

I copied the de_DE.po inside the /locales folder. 

When I try to execute the update_mo.pl script, I get the error 'ERROR: can not read current directory'.

I also tried to use sudo - same effect. 

Copying update_mo.pl to glpi/reservation gets rid of the error message but it seems to do nothing here.

**Comment by salleman33** [comment]
this script must be execute from reservation directory and you run it  with `perl tools/update_mo.pl`

**Comment by mahanovi** [comment]
Thank you for your answer.

Unfortunately it seems that the script doesn't do anything.

I don't get the Error message anymore, but no file is being created. (as far as I understand the script will create an *.mo file, right?) 

Also tried running it with sudo - same effect.

Is there something I missed?

**Comment by salleman33** [comment]
do you have the command "msgfmt" ? 
the script only run it, you can execute by yourself with `msgfmt locales/de_DE.po -o locales/de_DE.mo`

**Comment by mahanovi** [comment]
That has done the trick!
Thank you very much! 
Now my translation loads and is properly displayed.

However, there are still a few things that are displayed in English. 

For example under 'current reservations':

![image](https://user-images.githubusercontent.com/95433276/145058766-d403c9e2-13a2-4014-9bd6-c0a4e825eeaa.png)

And some things in the Plugin configuration (not _that_ important to us)

One last question: The time displayed for the reservations has a format like **<date> à <time>**

Is it possible to replace the **à** with another word?

**Comment by salleman33** [comment]
Could you use the last locales/glpi.pot (from git repository) ? You can update your de_DE.po with  this glpi.pot with the command : `msgmerge -U locales/de_DE.po locales/glpi.pot`

> Is it possible to replace the à with another word?
ok, I change it. It will be available in the next release.

**Comment by salleman33** [comment]
Hello, 
Could you translate the description on the file reservation.xml please ? and add some tags (at the end of this file) ? 
Thanks

**Comment by mahanovi** [comment]
I've added the description and the tags - thank you very much!
