### ISSUE TITLE
GLPI 10 compatibility?

### ISSUE THREAD

**Issue by mahanovi** [salleman33/reservation#58]
Hi!

We're testing the GLPI 10 beta and the plugin won't work properly.

Is it planned to release an update for 10.0?

**Comment by salleman33** [comment]
Hi, 
Yes of course, but I cannot give you a date. It depends of GLPI 10 release date and what are the changes in glpi core and the impacts on my plugin.

**Comment by jcovillers78114** [comment]
Bonjour,
Je me permet de déterrer le sujet.
GLPI10.0.0 étant disponible, est ce qu'une version de ton plugin est en vue ?
Merci

**Comment by salleman33** [comment]
Bonjour, 
j'ai commencé ! Il y a encore la partie "multi-edit"  à corriger. Vous pouvez tester et me remonter les bugs rencontrés en utilisant la branche master. Merci  !

**Comment by jcovillers78114** [comment]
Bonjour,
Pour le moment je n'ai pas trouvé de bug particulier.
Cependant, j'aimerai avoir si possible plus de détails sur les notifications car sur la version pour glpi 9.5 il n'y avait pas de notifications possible lorsque le réservant n'a pas restitué le matériel (acquittement non validé; zone rouge)
Merci !

**Comment by jcovillers78114** [comment]
J'ai trouvé des événements en doublons lorsqu'on lance la création d'une nouvelle notification

![2022-05-06 10_33_20-Window](https://user-images.githubusercontent.com/57490677/167096926-75a2a830-eea1-467c-b339-13787b7551fb.png)

**Comment by salleman33** [comment]
> J'ai trouvé des événements en doublons lorsqu'on lance la création d'une nouvelle notification
> 
> ![2022-05-06 10_33_20-Window](https://user-images.githubusercontent.com/57490677/167096926-75a2a830-eea1-467c-b339-13787b7551fb.png)

est-ce que ça le fait si vous désinstallez le plugin  et que vous le réinstallez ?

**Comment by carlosribeiro** [comment]
already have a date planned for the migration to GLPI 10?

**Comment by salleman33** [comment]
> already have a date planned for the migration to GLPI 10?

No sorry, but you can try the current code of 'master' branch
