### ISSUE TITLE
Show your own reservation first

### ISSUE THREAD

**Issue by kandohar** [salleman33/reservation#59]
I find it convenient to display my own reservations on top of others to easy access.

I developed it like the capture below, on another table because it was the easiest way.

Do you agree with that?
Do you want me to do it differently?

![reservation](https://user-images.githubusercontent.com/11271026/151796051-0dafb855-aef7-4639-a70a-3ca00b827e33.PNG)

**Comment by kandohar** [comment]
#60

**Comment by salleman33** [comment]
Hi,
I think that display your own reservations would be better in an other tab, like "my reservations". This tab could be enabled with a parameter on the plugin config view.
what do you think about that ?

**Comment by kandohar** [comment]
Hello, 
I totally agree, I updated my code with your idea.
It looks like the 'locales' are generated using a software so I didn't touch them, can you give me the guidelines to edit them?
And sorry about the mess in the code changes, I formatted the whole file so a lot of new spaces are added. If it's a problem, tell me, I can try to remove them.

![MyReservation](https://user-images.githubusercontent.com/11271026/152138021-1f99935b-b6cf-426d-8c8e-3e05a174f75a.PNG)
![Config](https://user-images.githubusercontent.com/11271026/152138022-b1012ed6-4a38-42f7-9117-198c4c308315.PNG)
.

**Comment by salleman33** [comment]
great ! 
for locales, you can use the script tools/extract_template.sh. It will update the glpi.pot and en_GB.po files. 
To update an other language, like FR, you can use this command : 
```
msgmerge locales/fr_FR.po locales/glpi.pot -o locales/fr_FR_new.po
```

Finally, you have to execute the script tools/update_mo.pl to compile po files.

**Comment by kandohar** [comment]
Ok, it works but it creates another fr_FR_**new**.mo/po files, so it doesn't seem to be used by the plugin.
Should I remove the "new" from the script? Or am I missing something?

**Comment by salleman33** [comment]
> Or do I have to delete the 'old' files, and just rename the 'new' ?

yes, you have to do it

**Comment by kandohar** [comment]
Ok, I did all that (extract, rename, modify, update). I then upload these files in my glpi test env.
But the label doesn't change. 
Is there something to do on the server ?

And I saw that sometimes you use `__('message', 'reservation')` and sometimes `_('message')`, is there a difference ?
I tried both but same result.

**Comment by kandohar** [comment]
Ok, my traductions in the po files were marked as "fuzzy", which makes them ignored by the update perl script.
I removed the "fuzzy" keyword and it's all good.

**Comment by kandohar** [comment]
Ok I think the PR is ready : #60 
I fixed some French translations too.

**Comment by salleman33** [comment]
Cool, thank you ! 

> And I saw that sometimes you use `__('message', 'reservation')` and sometimes `_('message')`, is there a difference ?
> I tried both but same result.

the first use word translation from the plugin. The second use the core glpi translations
