### ISSUE TITLE
Non conformité CSRF

### ISSUE THREAD

**Issue by B3uzz** [salleman33/reservation#6]
Bonjour,

Depuis la migration de mon GLPI (v0.90.3 > v0.93) et la mise à jour du plugin Réservation (v1.3.3 > v2.1.0), je ne peux plus installer ce dernier. J'ai une erreur de non conformité CSRF et je ne peux que nettoyer ce plugin. 
Petite précision, avant la migration de GLPI, j'ai désinstallé le plugin Réservation, afin de faire une réinstallation propre.

Une idée de l'origine de mon problème ?

(GLPI sur serveur DEBIAN)

**Comment by B3uzz** [comment]
Oui, j'ai le plugin "fusion inventory" d'installé et fonctionnel... Pareil que pour le plugin "réservation", je l'avais "nettoyer" avant de réinstaller sa dernière version.
Mise à part le répertoire à renommer en "reservation" dans le dossier "plugins" de GLPI, y a t'il d'autres modifications que dois effectuer ? Autre possibilité, peut-être que le "nettoyage" ne s'effectue pas correctement pour une raison qui m'échappe, y a t'il un moyen pour controler la manipulation ? (je pense éventuellement à aller regarder au niveau de la BDD voir si des tables du plugins existent toujours ?)

**Comment by B3uzz** [comment]
Problème résolu. 
J'ai supprimé le dossier "reservation" dans le répertoire "plugin" de GLPI
Je me suis assuré qu'il n'existait plus de tables appartenant au plugin dans ma BDD
J'ai relancé le service apache et le service mysql
J'ai copié à nouveau la dernière version du plugin "reservation" dans le répertoire "plugin" de GLPI
Relancé à nouveau les deux services
Cette fois-ci, je voyais bien apparaitre le plugin "réservation" dans GLPI, avec la possibilité de l'installer !
J'ignore l'origine du problème que j'ai rencontré, mais le simple fait d'avoir relancé mes services aura suffit à le résoudre.
Merci.

**Comment by salleman33** [comment]
ok, tant mieux. Effectivement, faut que je vois comment faire sur github pour générer des archives bien construites pour les releases.
