### ISSUE TITLE
Edit multiple reservations at once

### ISSUE THREAD

**Issue by kandohar** [salleman33/reservation#62]
Hello, 

I think it's useful to have a way to edit multiple reservations at once.

I plan to implement it like the picture below.
Adding a new link to edit the groups already formed when they have the same dates.
And then use a page, like the "edit" one, that deals with multiple items, where we can update the begin/end date.

Do you have an opinion about that?

![multiedit](https://user-images.githubusercontent.com/11271026/153202411-d0c7f9cc-d941-454b-ba05-76949405a05f.PNG)

**Comment by salleman33** [comment]
Hi, 
Yes it's a good idea !
Do you think you could avoid creating a new column for that ? (I think there is already a lot). Maybe with a button to enable multi-edit, who transform the colum "edit" with checkbox, or replace all the similars reservations edit lines to put "edit multiple" in place ?

**Comment by kandohar** [comment]
I agree, the second option seems better because we already have groups.

I'm still working on the edit form because the default glpi one doesn't handle that so I have to re-create it.

![enabled](https://user-images.githubusercontent.com/11271026/153395018-f0715be3-32db-4add-8fc8-d277f72d0617.PNG)
![disable](https://user-images.githubusercontent.com/11271026/153395024-618bda02-1834-45c5-9df6-5dc055a0fc85.PNG)

**Comment by kandohar** [comment]
I think it's ok.

I tried to implement as much thing as I can, but some stuff where not relevant.
I updated the locales too.

Don't hesitate if you have any feedback.

![multiedit](https://user-images.githubusercontent.com/11271026/153433793-52946aa9-c022-404b-9333-6f9b389e92cc.PNG)

**Comment by salleman33** [comment]
Ok, thank you.
I don't have a lot of time right now, but i try to look that asap.

**Comment by kandohar** [comment]
Hi, any news / ETA about my MR ?

**Comment by salleman33** [comment]
hi, 
I merge your PR and will make a new release in a few day
thanks for you job !
