### ISSUE TITLE
Error on plugin when Room reservation is uninstalled

### ISSUE THREAD

**Issue by jcervantes-sipecom** [salleman33/reservation#64]
## Steps to Reproduce

Hi,

I have only 3 reservation activated, 2 computers, and 1 reservation from Room Plugin

1. Install and active Room Plugin, create a Room and active Reservation. 
2. Make a reservation of the Room created before, do a check-in, without a check-out
3. Go to uninstall Plugin Room.
4. Go to Plugins > Reservation, the error appears:

![image](https://user-images.githubusercontent.com/56606032/155391324-f94fbbcb-4ce1-4f7d-8331-2a03c3c3594f.png)

```
PHP Notice (8): Undefined index: id in /var/www/html/glpi/plugins/reservation/inc/menu.class.php at line 305
PHP Notice (8): Undefined index: name in /var/www/html/glpi/plugins/reservation/inc/menu.class.php at line 305
PHP Notice (8): Undefined index: realname in /var/www/html/glpi/plugins/reservation/inc/menu.class.php at line 305
PHP Notice (8): Undefined index: firstname in /var/www/html/glpi/plugins/reservation/inc/menu.class.php at line 305
```

```
PHP Notice (8): Trying to get property 'fields' of non-object in /var/www/html/glpi/plugins/reservation/inc/menu.class.php at line 328
PHP Notice (8): Trying to access array offset on value of type null in /var/www/html/glpi/plugins/reservation/inc/menu.class.php at line 328
Uncaught Exception Error: Call to a member function getFormURLWithID() on bool in /var/www/html/glpi/plugins/reservation/inc/menu.class.php at line 328
```

## Expected Behaviour
When a reservation, as a computer, o a room from room's plugin, is uninstall, this should not affect the use of the reservation's plugin. The plugin should work with assets that actually are still there.

## Observed Behaviour
I have to install Room plugin again, and create a room, and activate the reservation of that room, for the plugin working:

![image](https://user-images.githubusercontent.com/56606032/155537645-d93f0dec-995b-446d-bddb-71796e2b6326.png)

![image](https://user-images.githubusercontent.com/56606032/155537756-1a7220e9-b7a4-460d-bcfd-55cf13bb2523.png)

## Context

As the plugin room was uninstalled, I have to install again, create a room, make a reservation, and thus the reservation plugins works again.

* GLPI version: 9.5.7
* Reservation plugin version: 2.3.8
* Operating System and version : Ubuntu 20.4
* Web server version and php version : Apache 7.4

**Comment by salleman33** [comment]
Hi, could you give more informations, or recreate an issue with the new issue template please.

**Comment by jcervantes-sipecom** [comment]
> Hi, could you give more informations, or recreate an issue with the new issue template please.

Hi, @salleman33, I have updated the case, I found the issue, and how I have resolved, but I don't know if this errors root in rooms' plugin, or it has to be an improvement of plugin's reservation

**Comment by salleman33** [comment]
ok, I suspect the problem come from rooms plugin : when you uninstall it, it does a destroy of all the tables in DB. But reservation plugin still keep reference with reservations of room. It would be better and cleaner if it delete all reservations made for a room.

otherwise, on my side, I could check and ignore if some reservation exists with an empty item.

**Comment by jackburton79** [comment]
I pushed a change on my glpi-10 branch which should fix the problem:
it deletes records in the glpi_reservations table for reservation_id associated with the room plugins.
Since it messes with glpi tables, I recommend people to try it in a test environment first.

**Comment by salleman33** [comment]
Hi, 
I wonder if using a hook would be better or not ? 
do you know if delete a glpi_reservation call a hook defined  for reservation ?

**Comment by jackburton79** [comment]
I don't know. Will have a look.

**Comment by jackburton79** [comment]
> Hi, I wonder if using a hook would be better or not ? do you know if delete a glpi_reservation on database call a hook defined for reservation ?

Hi, maybe I haven't got the full picture, but how would this help when uninstalling the room plugin ?

**Comment by salleman33** [comment]
Hi, 
your plugin add rooms item which can be a reservation_item which can be reserved, right? my plugin works by following  actions on reservations. I have a hook to clean my plugin_reservations when a reservation is deleted.
```php
$PLUGIN_HOOKS['item_purge']['reservation'] = ['Reservation' => 'plugin_item_purge_reservation'];
```
I don't know if calling `$DB->query('DELETE FROM glpi_reservations....` will call the hook or not. If not, declare a hook on room to delete all reservations made with this item could be a cleaner solution?

**Comment by jackburton79** [comment]
Thank you very much for the information.
I'm not the original developer of the room plugin, I'm just maintaining it to be able to use it on recent GLPI releases.
I'll try to see if I can implement your suggestions.
Thank you again.
