### ISSUE TITLE
Compatibilité plugins Reservation 2.3.8 avec Php8.0

### ISSUE THREAD

**Issue by ViLGranvRg** [salleman33/reservation#65]
Bonjour, 

Je viens de mettre a jour notre GLPI en version 9.5.7 avec une version PHP 8.0.
J'ai installé le plugins reservation mais il m'est impossible de l'utiliser. 
Lorsque je souhaite accéder à la partie Configuration, j'obtiens une page blanche. 

Est ce que le plugin est compatible avec php 8;0 ?

Merci de votre retour. 
Bonne journée

* GLPI version:
* Reservation plugin version: 2.3.8
* Operating System and version : Ubuntu 20.4
* Web server version and php version : 8.0

**Comment by salleman33** [comment]
Bonjour, 
Je n'ai pas testé avec php 8.0 mais ça ne serait pas étonnant qu'il y ait des problèmes. 
Quel genre de message d'erreur avez-vous ?

**Comment by ViLGranvRg** [comment]
Bonjour, 
Merci de votre retour. 
Je n'ai pas de message d'erreur qui apparait mais lorsque je souhaite configurer le plugin, une page blanche apparait. 
De plus, lorsque que je clique sur le plugins Reservation, aucune information ne s'affiche et je ne retrouve pas mon historique. 
Ci-dessous, la capture d'écran : 
![image](https://user-images.githubusercontent.com/102152540/159645602-e11f1163-610f-443b-af81-8545a3a129ba.png)

![image](https://user-images.githubusercontent.com/102152540/159645665-af19efd4-886c-40e5-9e5d-9f963e1c4cec.png)

Bonne journée

**Comment by salleman33** [comment]
est-ce qu'il y a messages dans les logs du serveur ?

**Comment by ViLGranvRg** [comment]
Voici, les log sous /glpi/files/_log/php-error.log 
![image](https://user-images.githubusercontent.com/102152540/159650492-f3808201-5ba2-416f-8ca2-6f6f755df08f.png)

**Comment by ViLGranvRg** [comment]
Bonjour, 
Pensez vous pouvoir rendre compatible le plugins avec le php8.0 ?
Merci de votre retour.

**Comment by salleman33** [comment]
Bonjour, 
oui dés que je peux... je pense regarder ça lorsque glpi 10 sera sorti, et lorsque je ferai la mise à jour de mon instance.
