### ISSUE TITLE
Reservations visible in Sub-Entity

### ISSUE THREAD

**Issue by mahanovi** [salleman33/reservation#67]
Hello!

I noticed that the reservations are also displayed in a sub-entity, although the corresponding users are not authorised to read this device category and the corresponding devices are not visible in the sub-entity.

Can this be changed?

The background is that we want to give a branch that has a sub-entity the possibility to manage its own device reservations as well. 

Now, however, they also see our reservations from the root entity, even though they can't edit them.

**Comment by salleman33** [comment]
Hi, 
I note your feedback. I hope to have some time soon to work on it..

**Comment by salleman33** [comment]
Hi, could you test with the commit d696297 ?

**Comment by mahanovi** [comment]
Hi!

With this commit everything works as it should.

Thank you so much for your good work :)
