### ISSUE TITLE
recherche par date  

### ISSUE THREAD

**Issue by sw1tch22** [salleman33/reservation#70]
## Steps to Reproduce

1.lorsque l'on fait un refresh (ou un acquittement de départ ou de retour) sur la page des réservations après une recherche par date, les dates de recherches se réinitialisent à la date du jour
## Expected Behaviour

garder les dates de recherche
## Technical Info

* GLPI version:
* Reservation plugin version: all
* Operating System and version : ubuntu 20.04
* Web server version and php version : apache 

## Analysis

 j'ai remarqué que la fonction qui gère cela : getFormDates() , doit définir la variable : glpi_plugin_reservation_form_dates , or ce n'est pas le cas

**Comment by sw1tch22** [comment]
ce code  (quick and dirty) règle le pb 


 public function getFormDates() {
      global $CFG_GLPI;
      $form_dates = [];

      if (isset($_SESSION['glpi_plugin_reservation_form_dates'])) {
         $form_dates = $_SESSION['glpi_plugin_reservation_form_dates'];
      }

      $day = date("d", time());
      $month = date("m", time());
      $year = date("Y", time());

      $begin_time = time();

      $planning_begin = $CFG_GLPI['planning_begin'];
      $planning_end = $CFG_GLPI['planning_end'];
      $planning_begin_time = explode(":", $planning_begin);
      $planning_end_time = explode(":", $planning_end);
      $planning_begin_date = date("Y-m-d H:i:s", mktime($planning_begin_time[0], $planning_begin_time[1], 00, $month, $day, $year));
      $planning_end_date = date("Y-m-d H:i:s", mktime($planning_end_time[0], $planning_end_time[1], 00, $month, $day, $year));

      $form_dates["begin"] = date("Y-m-d H:i:s", $begin_time);
      if ($planning_end_date > date("Y-m-d H:i:s", time())) {
         $form_dates['end'] = $planning_end_date;
      } else {
         $form_dates['end'] = date("Y-m-d H:i:s", mktime(23, 59, 00, $month, $day, $year));
      }

      if (isset($_SESSION['glpi_plugin_reservation_form_dates'])) {
         $form_dates = $_SESSION['glpi_plugin_reservation_form_dates'];
      }

      if (isset($_POST['date_begin'])) {
         $form_dates["begin"] = $_POST['date_begin'];
      }
      if (isset($_GET['date_begin'])) {
         $form_dates["begin"] = $_GET['date_begin'];
      }

      if (isset($_POST['date_end'])) {
         $form_dates["end"] = $_POST['date_end'];
      }
      if (isset($_GET['date_end'])) {
         $form_dates["end"] = $_GET['date_end'];
      }
      if (isset($_POST['nextday']) || isset($_GET['nextday'])) {
         $day = date("d", strtotime($form_dates["begin"]) + DAY_TIMESTAMP);
         $month = date("m", strtotime($form_dates["begin"]) + DAY_TIMESTAMP);
         $year = date("Y", strtotime($form_dates["begin"]) + DAY_TIMESTAMP);

         $form_dates["begin"] = date("Y-m-d H:i:s", mktime($planning_begin_time[0], $planning_begin_time[1], 00, $month, $day, $year));
         $form_dates["end"] = date("Y-m-d H:i:s", mktime($planning_end_time[0], $planning_end_time[1], 00, $month, $day, $year));
      }
      if (isset($_POST['previousday']) || isset($_GET['previousday'])) {
         $day = date("d", strtotime($form_dates["begin"]) - DAY_TIMESTAMP);
         $month = date("m", strtotime($form_dates["begin"]) - DAY_TIMESTAMP);
         $year = date("Y", strtotime($form_dates["begin"]) - DAY_TIMESTAMP);

              $form_dates["begin"] = date("Y-m-d H:i:s", mktime($planning_begin_time[0], $planning_begin_time[1], 00, $month, $day, $year));
         $form_dates["end"] = date("Y-m-d H:i:s", mktime($planning_end_time[0], $planning_end_time[1], 00, $month, $day, $year));
      }

      $_SESSION['glpi_plugin_reservation_form_dates'] = $form_dates;
   }

**Comment by salleman33** [comment]
en fait, à l'utilisation, je trouve ça plus confortable d'avoir la date du jour automatiquement, et donc lors d'un refresh. Qu'en pensez-vous ? 
Par contre, je suis d'accord que lors d'une action, c'est mieux de conserver les dates renseigner effectivement !
