### ISSUE TITLE
catégories personnalisés

### ISSUE THREAD

**Issue by El-Salmon60** [salleman33/reservation#75]
Bonjour, 

J'utilise actuellement glpi 10.0.5 et la version 2.4.1 de votre plugin. Je viens de rencontrer un problème au niveaux des catégories personnalisés, il m'est impossible de déplacer mes objets dans les différentes catégories que j'ai préalablement créé.

Merci de votre aide, je reste disponible pour fournir des informations complémentaires si besoin.

**Comment by salleman33** [comment]
Bonjour, 
Pouvez-vous essayer le code de la branche issue75 svp ?

**Comment by El-Salmon60** [comment]
Bonjour,

Je vais essayer cela sur notre serveur de test et je vous tiens au courant.

**Comment by El-Salmon60** [comment]
Je viens de mettre à jour le plugin avec la branche de code mentionné, l'ajout dans d'un matériel dans une catégorie fonctionne bien or la suppression d'un matériel d'une catégorie ne fonctionne pas. Quand je fais la modification et que je sauvegarde cela ne prend pas en compte mon changement.
