### ISSUE TITLE
Problème paramètre info-bulle

### ISSUE THREAD

**Issue by El-Salmon60** [salleman33/reservation#78]
Bonjour, je viens de mettre à jour le plugin avec la dernière version que vous avez publiée or, j'ai un problème avec un paramètre dans la configuration. Plus précisément le paramètre pour activer les info-bulles, quand je coche la case pour activer ce paramètre  et que je sauvegarde la case se décoche et le paramètre ne s'active donc pas.

**Comment by salleman33** [comment]
Bonjour, 
Je viens de tester sur mon instance en prod et sur une toute nouvelle, je ne rencontre pas ce problème. Avez-vous un message d'erreur dans les logs ou en activant le mode debug de glpi ?

**Comment by El-Salmon60** [comment]
En mode debug je rencontre les erreurs suivante :

PHP Warning (2): Undefined variable $toolTipConfig in /var/www/html/glpi/plugins/reservation/front/config.form.php at line 47

PHP Warning (2): foreach() argument must be of type array|object, null given in /var/www/html/glpi/plugins/reservation/front/config.form.php at line 47

PHP Warning (2): Undefined variable $tabConfig in /var/www/html/glpi/plugins/reservation/front/config.form.php at line 53

PHP Warning (2): foreach() argument must be of type array|object, null given in /var/www/html/glpi/plugins/reservation/front/config.form.php at line 53

**Comment by salleman33** [comment]
la définition de ces éléments se situe dans le fichier GLPI_ROOT/plugins/reservation/inc/includes.php
Est-ce que ce fichier existe chez vous et est au bon emplacement ?

**Comment by El-Salmon60** [comment]
Oui ce fichier est présent et au bon endroit.

je vous met en pièce-jointe ce qu'il contient.

![2023-05-11_14h53_14](https://github.com/salleman33/reservation/assets/78738958/43c7147d-58bf-4602-afff-427924e165ab)

**Comment by salleman33** [comment]
Pouvez-vous vérifier que le fichier `/var/www/html/glpi/plugins/reservation/front/config.form.php` contient bien à la ligne 8 : 
```
include_once GLPI_ROOT . "plugins/reservation/inc/includes.php";
```

Vous pouvez aussi essayer de copier/coller les lignes : 
```
$toolTipConfig = ["tooltip", "comment", "location", "serial", "inventory", "group", "man_model", "status"];
$tabConfig = ["tabmine", "tabcurrent", "tabcoming"];
```
 dans le fichier  `/var/www/html/glpi/plugins/reservation/front/config.form.php` à la ligne 9 par exemple.

**Comment by El-Salmon60** [comment]
La ligne 8 est bien présente, j'ai donc ajouté les deux lignes dans le fichier et le problème est résolu.

**Comment by El-Salmon60** [comment]
Merci pour votre aide et votre rapidité.

**Comment by salleman33** [comment]
Ok, 
Pouvez-vous m'indiquer la version de PHP que vous avez ?

**Comment by El-Salmon60** [comment]
PHP 8.0.25
