### ISSUE TITLE
nl2br(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by enryfantasy** [salleman33/reservation#82]
## Steps to Reproduce
Entering the "Available hardware" the page show the folloging error:
Warning: nl2br(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/plugins/reservation/inc/menu.class.php at line 708

## Expected Behaviour
No warning

## Technical Info

* GLPI version: 10.0.0.7
* Reservation plugin version: 2.4.4
* Operating System and version: docker container php8.2-apache
* Web server version and php version: php 8.2

## Analysis
I solved the problem by editing line 708 in file  /var/www/html/plugins/reservation/inc/menu.class.php.

Changed from:
<code>echo "<td>" . nl2br($reservation_item['comment']) . "</td>";</code>

to:
<code>echo "<td>" . nl2br($reservation_item['comment'] ?? '') . "</td>";</code>

**Comment by salleman33** [comment]
Thanks !
