### ISSUE TITLE
Configuration des catégories

### ISSUE THREAD

**Issue by Kzou** [salleman33/reservation#83]
Bonjour,

Je voulais tester les catégories, mais quand j'essaie de les configurer, je me retrouve avec cet écran, sans possibilité d'ajouter des éléments : 
![cat](https://github.com/salleman33/reservation/assets/4509291/afbbf027-fac4-4da0-a7f2-1c5fe89ed6a0)

D'ailleurs, je n'arrive pas à voir les fonctionnalités dans la réservation liées à ces catégories ?

Merci et bonne journée!

**Comment by salleman33** [comment]
Bonjour, 
Est-ce que l'item '0">' est un item existant ? 
Si vous cliquez sur un item de la liste de gauche, et que vous cliquer sur le bouton de la flèche de droite, il se passe quelque chose ?

**Comment by Kzou** [comment]
Bonjour,

Non je n'ai pas d'item qui porte ce nom, et je ne peux pas cliquer sur les noms dans la colonne de gauche, c'est comme si ce n'était que du texte "brut" affiché dans la page.

Merci

**Comment by salleman33** [comment]
Bonjour, 

Pouvez-vous tester avec un autre navigateur ? 
Cette partie génère de l'HTML ,  il faudrait voir à quoi ressemble le code source HTML. 
Regardez aussi les logs du navigateur et/ou les logs de GLPI.

**Comment by Kzou** [comment]
Bonjour,

en effet j'ai un warning PHP quand j'affiche la page : 

`mod_fcgid: stderr: PHP Warning:  A non-numeric value encountered in /var/www/clients/client1/web7/web/plugins/reservation/inc/config.class.php on line 96, referer`

Même chose avec chrome et firefox pour info.

**Comment by salleman33** [comment]
Bonjour, 
c'est seulement un warning, le problème ne doit pas venir de là. 
Pouvez-vous renseigner les informations techniques : 
* GLPI version:
* Reservation plugin version:
* Operating System and version :
* Web server version and php version :

**Comment by Kzou** [comment]
Ok ! Voici les infos : 
GLPI version 10.0.7
Reservation version 2.4.4
Debian 10
Apache version 2.4.38
PHP version 7.4

Voici une capture d'écran du 0 qui se balade en début de liste : 

![form-image](https://github.com/salleman33/reservation/assets/4509291/68278cc5-8857-48fd-a8d8-58b9c287233e)

Et le début du code du formulaire (je ne sais pas si c'est suffisant ?) : 
`<form id="formPluginReservationConfigs" method="post" action="/plugins/reservation/front/config.form.php"><div class="center"><script>$('#formPluginReservationConfigs').submit( function(eventObj) {
            var items = document.getElementById('select_selectedItems');
            for (let i = 0; i < items.options.length; i++) {
                var item = items.options[i];
                $('<input />').attr('type', 'hidden')
                    .attr('name', 'option_selectedItems_'+item.value)
                    .attr('value',item.value)
                    .appendTo('#formPluginReservationConfigs');
            }
            return true;
        });</script><h1>Zoom</h1><table class="tab_cadre_fixe" cellpadding="2"><input type="hidden" name="configCategoryItems" value="Zoom"><tbody><tr><th style="text-align: right;" class="">Available Items</th><th class=""></th><th style="text-align: left;">Selected Items</th></tr><tr class=""><td style="text-align: right;"><div id="div_availableItems">0"&gt;<option value="60">Appareil photo 01</option>`

**Comment by salleman33** [comment]
ok, il y a de grandes chances que le problème vienne de la version de PHP.
Pouvez-vous essayer de modifier le code du fichier inc/config.class.php, ligne 96 : 
```
echo '<select id="select_availableItems" size="' . count($availableItems_array) + count($selectedItems_array) . '">';
```
et la remplacer par  :
```
echo '<select id="select_availableItems" size="' . (count($availableItems_array) + count($selectedItems_array)) . '">';
```

**Comment by Kzou** [comment]
Oh ! Super c'est bien ça !
Pour info, il faut aussi modifier la ligne 117 (même chose), qui correspond à la liste de droite.

Merci beaucoup !
