### ISSUE TITLE
acknowledge/release of equipement

### ISSUE THREAD

**Issue by Shiikei** [salleman33/reservation#87]
## Steps to Reproduce

1. Acknowledge return of equipment
2. try to reserve the equipment just released not showing in list
3.

## Expected Behaviour

Possibility to reserve equipment immediately after the return is confirmed.

## Context

When we want to reserve equipment that just came back to give it to other person who just asked it. Equipment not directly show in the list but after a few minute it's possible to reserve them.
## Technical Info

In this case, it's not really a bug i think but can we adjust the timer of rechecking the availability of equipment?

* GLPI version: 10.0.12 
* Reservation plugin version: 2.4.4
* Operating System and version : debian 11
* Web server version and php version : php 8.2
I write in english for community but we can go in french.

**Comment by salleman33** [comment]
Hi, 
What appens if you click on the refresh button on the right (cf image below) after the checkout action ? 
![image](https://github.com/salleman33/reservation/assets/37148072/6e87332f-38c2-4073-a500-95b6b2fcd59c)

**Comment by Shiikei** [comment]
Yes, it works, but in the version we saw, the bug occurred when we checked out. It was showing the time of the checkout instead of 'checked out.' Maybe a colleague of mine did an update on the plugin.

I bothered you for nothing.

Have a nice day
