### ISSUE TITLE
Exception Error: Call to a member function getConnexityItem() on bool 

### ISSUE THREAD

**Issue by flonou** [salleman33/reservation#91]
## Steps to Reproduce
1. Cron task CheckReservation.

## Expected Behaviour
No error should happen

## Observed Behaviour
An exception was thrown : 
Uncaught Exception Error: Call to a member function getConnexityItem() on bool in /var/www/glpi/plugins/reservation/inc/task.class.php at line 139

## Technical Info
N/A

* GLPI version:
* Reservation plugin version: 9.4.4
* Operating System and version :
* Web server version and php version :

## Analysis
The issue seems to happen when trying to check reservations expiration.
The method checkExpiration has two embeded foreach loops. The second one will check if a late reservation can be replaced by another one from the same user and delete the uneccessary reservation https://github.com/salleman33/reservation/blob/9c0c2fcdff5180ed86bbbec4bd8753c216f95950/inc/task.class.php#L187
The first foreach loop may however still check that deleted reservation, resulting in $reservationitems to be false (because getConnexityItem returns false if no result is found) on line https://github.com/salleman33/reservation/blob/9c0c2fcdff5180ed86bbbec4bd8753c216f95950/inc/task.class.php#L139C22-L139C38

This simplest patch would be to check the value of $reservationitems with something like
```
if($reservationitems)
    continue
```
added after line https://github.com/salleman33/reservation/blob/9c0c2fcdff5180ed86bbbec4bd8753c216f95950/inc/task.class.php#L138

Deleting the reservation from the list after it has been removed from GLPI could be a bit more problematic because it requires to modify the collection while iterating over it.

**Comment by salleman33** [comment]
Hi, 
#92 should resolve this issue.

Thanks
